---
plugin: google.cloud.gcp_compute
projects:
  - project-931d2b58-2ab3-43b7-bcd # name of the project
zones:
  - europe-central2-a
auth_kind:  serviceaccount
service_account_file: service_account_file.json # path to service account .json file (can be changed to environment variable alternative)
keyed_groups:
  - prefix: app
    key: labels.app
#groups:
#  remote: "'nodejs-dockerized' in (labels|list)"
