- name: Check SSH port connectivity
  hosts: app_nodejs_dockerized
  gather_facts: false
  vars_files:
    - roles/ssh/vars/main.yaml
  tasks:
    - block:
      - name: Include SSH check task
        ansible.builtin.include_tasks: ssh_check.yaml
      check_mode: false
      tags: 
        - always


- name: Test GCP connectivity
  hosts: app_nodejs_dockerized
  become: true
  become_method: sudo
  tasks:
    - name: Test connectivity 
      ansible.builtin.ping:

    - name: Execute "base" role
      block:
        - include_role: 
            name: base
      tags: 
        - base
        - first_step

    - name: Execute "firewall" role
      block:
        - include_role:
            name: firewall
      tags:
        - firewall
        - second_step

    - name: Execute "ssh" role
      block:
        - include_role:
            name: ssh
      tags:
        - ssh
        - third_step

    - name: Execute "app" role
      block:
        - include_role:
            name: app
      tags:
        - app
        - fourth_step
