---
- name: Check if default SSH port is open
  local_action: ansible.builtin.wait_for
  args:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 0
    timeout: 10
  #delegate_to: localhost
  ignore_errors: true
  register: ssh_default_port_check
- name: Check if custom SSH port is open
  local_action: ansible.builtin.wait_for
  args:
    host: "{{ inventory_hostname }}"
    port: "{{ ssh_custom_port }}"
    state: started
    delay: 0
    timeout: 10
  #delegate_to: localhost
  ignore_errors: true
  register: ssh_custom_port_check
  when: ssh_default_port_check.failed

- name: Set ansible_port to custom port
  ansible.builtin.set_fact:
    ansible_port: "{{ ssh_custom_port }}"
  when: ssh_custom_port_check.state is defined and ssh_custom_port_check.state == "started"
- name: Set ansible_port to default port
  ansible.builtin.set_fact:
    ansible_port: 22
  when: ssh_default_port_check.state is defined and ssh_default_port_check.state == "started"

- name: Gather facts
  ansible.builtin.gather_facts:

