---
- name: Check if custom SSH port is open
  ansible.builtin_wait_for:
    host: "{{ ansible_host }}"
    port: "{{SSH_CUSTOM_PORT}}"
    state: started
    delay: 0
    timeout: 3
  deligate_to: localhost
  ignore_errors: true
  register: CUSTOM_SSH_PORT_CHECK

- name: Check if default SSH port is open
  ansible.builtin_wait_for:
    host: "{{ ansible_host }}"
    port: 22
    state: started
    delay: 0
    timeout: 3
  deligate_to: localhost
  ignore_errors: true
  register: DEFAULT_SSH_PORT_CHECK
  when: CUSTOM_SSH_PORT_CHECK.failed

- name: Set ansible_port to custom port
  ansible.builtin.set_fact:
    ansible_port: "{{ CUSTOM_SSH_PORT }}"
  when: CUSTOM_SSH_PORT_CHECK.state is defined and CUSTOM_SSH_PORT_CHECK.state == "started"
- name: Set ansible_port to default port
  ansible.builtin.set_fact:
    ansible_port: 22
  when: DEFAULT_SSH_PORT_CHECK.state is defined and DEFAULT_SSH_PORT_CHECK.state == "started"

- name: Gather facts
  ansible.builtin.gather_facts:

