version: "3"

tasks: 
  push-version-tag:
    desc: "Use git describe to create a tag based on the latest release tag by push"
    vars:
      GITHUB_REF: "{{.CLI_ARGS}}"
    cmds:
      - |
        set -euo pipefall
        GITHUB_REF={{.GITHUB_REF}}
        VERSION="${GITHUB_REF#refs/tags/}"
        PUSH_TAG="komardinecplusplus/nodejs-dockerized:${VERSION}"
        echo "$PUSH_TAG"
    silent: true
        
  manual-version-tag:
    desc: "Use specified by hand version to create image tag"
    vars:
      VERSION: "{{.CLI_ARGS}}"
    cmds:
      - |
        echo "komardinecplusplus/nodejs-dockerized:{{.VERSION}}"

